# Generated by Django 5.0.4 on 2024-04-28 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='VerifyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField()),
                ('verify_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('count_voices', models.IntegerField(default=0)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Main.district')),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.region')),
            ],
        ),
    ]
