# Generated by Django 5.0.4 on 2024-04-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_district_id_alter_region_id_alter_voice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
